name: Development Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: adopt
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/
        
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: "1.20.4_1.0.9.3"
          prerelease: true
          title: "1.20.4 | 1.0.9.2"
          files: |
            ./build/libs/*.jar
